services:
  spy:
    image: ghcr.io/wormhole-foundation/guardiand:v2.8.10.1
    command:
      - "spy"
      - "--nodeKey"
      - "/node.key"
      - "--spyRPC"
      - "[::]:7072"
      - "--bootstrap"
      - "/dns4/wormhole-testnet-v2-bootstrap.certus.one/udp/8999/quic/p2p/12D3KooWBY9ty9CXLBXGQzMuqkziLntsVcyz4pk1zWaJRvJn6Mmt"
      - "--network"
      - "/wormhole/testnet/2/1"
      - "--logLevel"
      - "debug"
  price-service:
    image: public.ecr.aws/pyth-network/xc-server:v1.0.0
    environment:
      - SPY_SERVICE_HOST=spy:7072
      - SPY_SERVICE_FILTERS=[{"chain_id":1,"emitter_address":"f346195ac02f37d60d4db8ffa6ef74cb1be3550047543a4a9ee9acf4d78697b0"}]
      - REST_PORT=4200
      - PROM_PORT=8081
      - READINESS_SPY_SYNC_TIME_SECONDS=60
      - READINESS_NUM_LOADED_SYMBOLS=8
      - LOG_LEVEL=debug
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:4200/ready",
        ]
      start_period: 60s
    depends_on:
      - spy
  price-pusher:
    build:
      context: .
    # Uncomment this line (and comment out the above lines) to use a prebuilt image. Replace <version>
    # with the latest released image of the EVM price pusher from this repo release page:
    # https://github.com/pyth-network/pyth-js/releases
    # image: public.ecr.aws/pyth-network/xc-evm-price-pusher:v<version>
    restart: always
    command:
      - "--"
      - "--evm-endpoint"
      # Replace this with RPC endpoint URL for the EVM network.
      - "https://data-seed-prebsc-1-s1.binance.org:8545"
      - "--mnemonic-file"
      - "/mnemonic"
      - "--pyth-contract"
      # Replace this with the Pyth contract address. Provide the network name on which Pyth is deployed
      # or the Pyth contract address if you use a local network
      - "bnb_testnet"
      - "--price-endpoint"
      - "http://price-service:4200"
      - "--price-config-file"
      - "/price_config"
    configs:
      - mnemonic
      - price_config
    depends_on:
      price-service:
        condition: service_healthy
configs:
  mnemonic:
    file: ./path/to/mnemonic.txt # Replace this with the path to the mnemonic file
  price_config:
    file: ./price-config.testnet.sample.yaml # Replace this with the path to the price configuration file
