name: Publish Pyth SDK to crates.io

on:
  pull_request:
  push:
    branches: [main]
jobs:
  publish-pyth-common-js:
    name: Publish Pyth Common JS
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
        working-directory: "pyth-common-js"
      - run: npm run build
        working-directory: "pyth-common-js"
  publish-pyth-evm-js:
    name: Publish Pyth EVM JS
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
        working-directory: "pyth-evm-js"
      - run: npm run build
        working-directory: "pyth-evm-js"
  publish-pyth-terra-js:
    name: Publish Pyth Common JS
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
        working-directory: "pyth-terra-js"
      - run: npm run build
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        working-directory: "pyth-terra-js"
