name: Build Pyth JS packages

on:
  pull_request:
  push:
    branches: [main]
jobs:
  build-pyth-common-js:
    name: Build Pyth Common JS
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
        working-directory: "pyth-common-js"
      - run: npm run build
        working-directory: "pyth-common-js"
      - run: npm run prepublishOnly
        working-directory: "pyth-common-js"
  build-pyth-evm-js:
    name: Build Pyth EVM JS
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      # This step is required for npm 14 to work for installing this
      - name: Reconfigure git to use HTTP authentication
        run: >
          git config --global url."https://github.com/".insteadOf
          ssh://git@github.com/
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
        working-directory: "pyth-evm-js"
      - run: npm run build
        working-directory: "pyth-evm-js"
      - run: npm run prepublishOnly
        working-directory: "pyth-evm-js"
  build-pyth-aptos-js:
    name: Build Pyth Aptos JS
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      # This step is required for npm 14 to work for installing this
      - name: Reconfigure git to use HTTP authentication
        run: >
          git config --global url."https://github.com/".insteadOf
          ssh://git@github.com/
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
        working-directory: "pyth-aptos-js"
      - run: npm run build
        working-directory: "pyth-aptos-js"
      - run: npm run prepublishOnly
        working-directory: "pyth-aptos-js"
  build-pyth-terra-js:
    name: Build Pyth Common JS
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
        working-directory: "pyth-terra-js"
      - run: npm run build
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        working-directory: "pyth-terra-js"
      - run: npm run prepublishOnly
        working-directory: "pyth-terra-js"
