name: Publish Pyth JS packages

on:
  release:
    types:
      - created
jobs:
  publish-pyth-common-js:
    name: Publish Pyth Common JS
    if: ${{ startsWith(github.ref, 'refs/tags/pyth-common-js-v') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          registry-url: "https://registry.npmjs.org"
      - run: npm ci
        working-directory: "pyth-common-js"
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        working-directory: "pyth-common-js"
  publish-pyth-evm-js:
    name: Publish Pyth EVM JS
    if: ${{ startsWith(github.ref, 'refs/tags/pyth-evm-js-v') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          registry-url: "https://registry.npmjs.org"
      - run: npm ci
        working-directory: "pyth-evm-js"
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        working-directory: "pyth-evm-js"
  publish-pyth-aptos-js:
    name: Publish Pyth Aptos JS
    if: ${{ startsWith(github.ref, 'refs/tags/pyth-aptos-js-v') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          registry-url: "https://registry.npmjs.org"
      - run: npm ci
        working-directory: "pyth-aptos-js"
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        working-directory: "pyth-aptos-js"
  publish-pyth-terra-js:
    name: Publish Pyth Common JS
    if: ${{ startsWith(github.ref, 'refs/tags/pyth-terra-js-v') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          registry-url: "https://registry.npmjs.org"
      - run: npm ci
        working-directory: "pyth-terra-js"
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        working-directory: "pyth-terra-js"
